name = "confidant-web"
compatibility_date = "2024-09-23"

[pages]
pages_build_output_dir = "src/frontend/dist"
build_command = "npm install -g npm@9.6.7 && cd src/frontend && npm install && npm run build"
build_output_dir = "src/frontend/dist"

[env]
NODE_VERSION = "18.19.0"
NPM_VERSION = "9.6.7"
VITE_API_URL = "https://confidant-api-development.kevin-mcgovern.workers.dev"
VITE_CLOUDFLARE_ACCOUNT_ID = "315111a87fcb293ac0efd819b6e59147"

# API Configuration
[env.api]
name = "confidant-api"
main = "src/api/index.ts"
compatibility_flags = ["nodejs_compat"]

[env.api.vars]
ENVIRONMENT = "development"

[env.api.production]
vars = { ENVIRONMENT = "production" }

[[env.api.production.d1_databases]]
binding = "DB"
database_name = "confidant-db"
database_id = "c3aec830-dd14-4cc6-a733-ac25cf7e3628"

[[env.api.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "confidant-storage"

[env.api.staging]
vars = { ENVIRONMENT = "staging" }

[[env.api.staging.d1_databases]]
binding = "DB"
database_name = "confidant-db"
database_id = "c3aec830-dd14-4cc6-a733-ac25cf7e3628"

[[env.api.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "confidant-storage"

[env.api.development]
vars = { ENVIRONMENT = "development" }

[[env.api.development.d1_databases]]
binding = "DB"
database_name = "confidant-db"
database_id = "c3aec830-dd14-4cc6-a733-ac25cf7e3628"

[[env.api.development.r2_buckets]]
binding = "STORAGE"
bucket_name = "confidant-storage"
preview_bucket_name = "confidant-storage-dev" 