name = "confidant-api"
main = "index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
API_URL = "https://confidant-api.kevin-mcgovern.workers.dev"
FRONTEND_URL = "https://confidant-web.pages.dev"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "confidant-db"
database_id = "c3aec830-dd14-4cc6-a733-ac25cf7e3628" 