name = "confidant-api"
main = "src/index.ts"
compatibility_date = "2024-02-20"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
API_URL = "https://confidant-api.kevin-mcgovern.workers.dev"
FRONTEND_URL = "https://confidant-web.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "confidant-db"
database_id = "c3aec830-dd14-4cc6-a733-ac25cf7e3628"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "confidant-storage"
preview_bucket_name = "confidant-storage-dev" 