name = "confidant-api"
main = "src/index.ts"
compatibility_date = "2024-02-20"

[vars]
JWT_SECRET = "your-secret-key"
FRONTEND_URL = "https://confidant-web.pages.dev"
API_URL = "https://api.confidant.app"

# OAuth Configuration
GOOGLE_CLIENT_ID = "your-google-client-id"
GOOGLE_CLIENT_SECRET = "your-google-client-secret"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "confidant-db"
database_id = "c3aec830-dd14-4cc6-a733-ac25cf7e3628" 