name = "confidant-web"
compatibility_date = "2024-09-23"

[build]
command = "npm ci && npm run build"
cwd = "."

[site]
bucket = "./dist"

[pages]
pages_build_output_dir = "dist"
build_command = "npm ci && npm run build" 