name = "confidant-web"
compatibility_date = "2024-09-23"

[build]
command = "npm install && npm run build"
cwd = "src/frontend"

[site]
bucket = "src/frontend/dist"

[pages]
pages_build_output_dir = "src/frontend/dist" 